/* ============================================================
   baseline.mjs — the numbers of this repository, counted rather than remembered.

   The baseline table in CLAUDE.md used to be written by hand, and it rotted
   without anybody deciding anything: it claimed twelve readings when there
   were twenty-four, and named a line count from several refactors ago. A
   number nobody can reproduce is not a baseline, it is a memory of one.

   So the table is printed by this script, in the exact Markdown the document
   carries, and the document holds the command next to it. Rewriting the
   section is a copy of this output; noticing that it has drifted is a
   diff.

   WHAT IS NOT HERE, and why. Test runs and coverage are not counted: they
   are what the suites report when they actually execute, and a static count
   of `test(` calls would be a different number wearing the same name. Those
   rows keep their own command in the document (`npm test`, `npm run
   test:dom`, `node scripts/coverage.mjs`).

   Deterministic on purpose: no clock, no ordering by anything but name, so
   two runs on the same tree print the same bytes. That is what makes the
   gate in the Definition of Done checkable at all.

   Usage: node scripts/baseline.mjs
   ============================================================ */
import { readFileSync, readdirSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

/* The languages the course speaks, in the order the document lists them. */
const LANGS = ["pl", "en", "es", "fr", "de"];

/* ---------------- The course data, in a sandbox ---------------- */

const levels = [];
const byCode = {};
const ui = {};
const wszystkieCzytanki = [];

const sandbox = {
  console,
  LINGUAI: {
    registerLevel(lv) { lv.units = lv.units || []; levels.push(lv); byCode[lv.code] = lv; },
    addUnits(code, units) { if (byCode[code]) byCode[code].units = byCode[code].units.concat(units); },
    /* The interface dictionaries announce themselves through the same
       object as the course data, so one sandbox collects both. */
    addUI(lang, obj) { ui[lang] = obj; },
    /* Every reading now arrives this way, the short ones and the long ones
       alike. Which is which is decided by WHEN they arrive: readings.js runs
       first, the library files after, so the split below is a position in
       this list rather than a guess at an id. */
    addReadings(lista) { wszystkieCzytanki.push(...(lista || [])); }
  }
};
sandbox.window = sandbox;
vm.createContext(sandbox);

function run(path) {
  vm.runInContext(readFileSync(join(ROOT, path), "utf8"), sandbox, { filename: path });
}

/**
 * A global the data files are supposed to have registered.
 *
 * Loudly, because the failure it prevents is specific and has already
 * happened to this table by other means: rename `window.READINGS`, or move a
 * file out of the list above, and every count built on it collapses to zero.
 * A zero here does not look like a bug, it looks like a number — and the
 * whole point of this script is that the document stops carrying numbers
 * nobody can reproduce.
 */
function need(name) {
  const v = sandbox[name];
  if (v === undefined) {
    console.error(`baseline: brak globalnej ${name} — plik danych zmienił nazwę albo nie został wczytany`);
    process.exit(1);
  }
  return v;
}

const lessonFiles = readdirSync(join(ROOT, "data", "core"))
  .filter((f) => /^[abc]\d-\d+\.js$/.test(f))
  .sort();

["curriculum-index.js", ...lessonFiles, "conversations.js", "grammar-reference.js",
  "phonetics.js", "readings.js", "writing.js", "interference.js", "cils.js", "frequenza.js"]
  .forEach((f) => run(join("data", "core", f)));

/* The dividing line: everything registered up to here came from
   readings.js, everything after it from the library. */
const ILE_KROTKICH = wszystkieCzytanki.length;

/* The library, one file per level: it does not load at startup in the
   browser either, and here it has to be asked for by name. */
readdirSync(join(ROOT, "data", "core"))
  .filter((f) => /^library-[abc]\d\.js$/.test(f))
  .sort()
  .forEach((f) => run(join("data", "core", f)));

const czytanki = wszystkieCzytanki.slice(0, ILE_KROTKICH);
const biblioteka = wszystkieCzytanki.slice(ILE_KROTKICH);

/* Not in data/core/: it is generated by build_audio.py and sits next to it. */
run(join("data", "audio-index.js"));

LANGS.forEach((l) => run(join("data", "i18n", `ui-${l}.js`)));

/* ---------------- Counting ---------------- */

/** Every lesson of every unit, unit tests included: they hold exercises too. */
function lessons() {
  const out = [];
  levels.forEach((lv) => (lv.units || []).forEach((u) => {
    (u.lessons || []).forEach((l) => out.push(l));
    if (u.test) out.push(u.test);
  }));
  return out;
}

function count(dir, filter) {
  return readdirSync(join(ROOT, dir)).filter(filter);
}

function bytesOf(dir, files) {
  return files.reduce((n, f) => n + statSync(join(ROOT, dir, f)).size, 0);
}

/**
 * Whole MiB of CONTENT, not of occupied disk.
 *
 * The two differ by about a fifth here: the files average eleven kilobytes
 * and the filesystem hands out four-kilobyte blocks, so `du` reports 45
 * where the bytes say 37. ADR-010 counts bytes and its thresholds are read
 * against bytes, so the row says bytes and names them.
 */
function mib(bytes) { return Math.round(bytes / (1024 * 1024)); }

/** Every mp3 under audio/, which is two levels deep: audio/<xx>/<hash>.mp3 */
function recordings() {
  const base = join(ROOT, "audio");
  let files = 0, bytes = 0;
  readdirSync(base).sort().forEach((sub) => {
    const p = join(base, sub);
    if (!statSync(p).isDirectory()) return;
    readdirSync(p).forEach((f) => {
      if (!f.endsWith(".mp3")) return;
      files++;
      bytes += statSync(join(p, f)).size;
    });
  });
  return { files, bytes };
}

const HASH_CHARS = 16;   /* one FNV-1a 64-bit digest, as build_audio.py writes it */

function engine() {
  const dir = "assets/js";
  const files = count(dir, (f) => f.endsWith(".js")).sort();
  /* Newlines, so the number agrees with `wc -l`. Counting the pieces of a
     split gives one more per file, and a baseline that disagrees with the
     obvious command to check it is worse than no baseline. */
  const lines = files.reduce((n, f) => {
    const src = readFileSync(join(ROOT, dir, f), "utf8");
    return n + src.split("\n").length - (src.endsWith("\n") ? 1 : 0);
  }, 0);
  return { files: files.length, lines };
}

const all = lessons();
const exercises = all.reduce((n, l) => n + (l.exercises || []).length, 0);
const vocab = all.reduce((n, l) => n + (l.vocab || []).length, 0);
const units = levels.reduce((n, lv) => n + (lv.units || []).length, 0);

const readings = wszystkieCzytanki;

const types = {};
all.forEach((l) => (l.exercises || []).forEach((e) => { types[e.t] = (types[e.t] || 0) + 1; }));
readings.forEach((r) => (r.questions || []).forEach((q) => {
  types[q.t] = (types[q.t] || 0) + 1;
}));

/* The reference is a list of GROUPS, each holding the entries the course
   links to from a lesson tag. What the document counts is the entries. */
const grammarEntries = need("GRAMMAR_REF")
  .reduce((n, g) => n + (g.items || []).length, 0);

/* The library in two numbers, because "six texts" says nothing about how
   much Italian that is, and the amount is the whole point of having it. */
const zdaniaBiblioteki = biblioteka.reduce((n, r) => n + (r.sentences || []).length, 0);
const slowaBiblioteki = biblioteka.reduce((n, r) =>
  n + (r.sentences || []).reduce((m, z) => m + z.split(/\s+/).filter(Boolean).length, 0), 0);

const rec = recordings();
const indexed = String(need("AUDIO_INDEX")).length / HASH_CHARS;
const fonts = count("assets/fonts", (f) => f.endsWith(".woff2")).sort();
const eng = engine();

/* Every language carries the same keys; a difference is parity.mjs's job to
   report, so here the count of the first one is the count. */
const keys = Object.keys(ui[LANGS[0]] || {}).length;

/* ---------------- The table ---------------- */

const rows = [
  ["Jednostki / lekcje / ćwiczenia", `${units} / ${all.length} / ${exercises}`],
  ["Pozycje słownika / rozmowy / hasła gramatyczne",
    `${vocab} / ${need("CONVERSATIONS").length} / ${grammarEntries}`],
  ["Czytanki / zadania pisane / zbiory par minimalnych",
    `${czytanki.length} / ${need("WRITING").length} / ${need("PHONETICS").length}`],
  ["Biblioteka: teksty / zdania / słowa",
    `${biblioteka.length} / ${zdaniaBiblioteki} / ${slowaBiblioteki}`],
  ["Typy ćwiczeń obecnych w danych", String(Object.keys(types).length)],
  ["Nagrania", `${rec.files} plików mp3, ${mib(rec.bytes)} MiB bajtów; ${indexed} skrótów w indeksie`],
  ["Klucze interfejsu na język", `${keys} × ${LANGS.length} języków`],
  ["Kroje pisma", `${fonts.length} plików woff2 w assets/fonts/, ${Math.round(bytesOf("assets/fonts", fonts) / 1024)} KB`],
  ["Pliki silnika", `${eng.files} w assets/js/, ${eng.lines} linii`]
];

const CMD = "`node scripts/baseline.mjs`";
console.log("| Co | Ile | Polecenie |");
console.log("|---|---|---|");
rows.forEach(([label, value]) => console.log(`| ${label} | ${value} | ${CMD} |`));
