/* ============================================================
   FSRS against the reference implementation.

   This IS the correctness criterion for `assets/js/fsrs.js` - the only one
   this project can have. The gain from FSRS is measured on a student's
   review history, and the course has neither a server nor telemetry, so the
   parameters stay at their defaults and "fewer reviews at the same
   retention" is not checkable here. What is checkable is that the numbers
   agree with py-fsrs, and that is what we check.

   Vectors: `tests/unit/fsrs-vectors.json`, generated by
   `uv run --script scripts/gen_fsrs_vectors.py` with interval fuzzing
   switched off. The file is versioned because it is a contract, not an
   artefact: when the FSRS version goes up we look at the git diff first.
   ============================================================ */
import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { loadEngine, ROOT } from "./_harness.mjs";

const WEKTORY = JSON.parse(readFileSync(join(ROOT, "tests/unit/fsrs-vectors.json"), "utf8"));

/* Six decimal places: that is what the generator writes. Beyond that it is
   floating-point noise, different in Python and in V8. */
const TOL = 1e-6;

function silnik() {
  const box = loadEngine({ files: ["assets/js/fsrs.js"] });
  return box.sandbox.Fsrs;
}

const OCENY = { again: 1, hard: 2, good: 3, easy: 4 };

describe("fsrs: agreement with py-fsrs", () => {
  /* Arrays from the sandbox have a prototype from another realm, so a strict
     deepEqual rejects [1] against [1]. We copy through Array.from because we
     compare content, not prototype identity - the same trick as in
     state.test.mjs. */
  const zZewnatrz = xs => Array.from(xs);

  test("the default configuration is the same as in the reference", () => {
    const F = silnik();
    assert.deepEqual(zZewnatrz(F.DOMYSLNE.parametry), WEKTORY.parametry, "21 FSRS-6 parameters");
    assert.equal(F.DOMYSLNE.retencja, WEKTORY.desiredRetention);
    assert.deepEqual(
      zZewnatrz(F.DOMYSLNE.krokiNauki).map(ms => ms / 1000),
      WEKTORY.learningStepsSekund
    );
    assert.deepEqual(
      zZewnatrz(F.DOMYSLNE.krokiPowtornejNauki).map(ms => ms / 1000),
      WEKTORY.relearningStepsSekund
    );
    assert.equal(F.DOMYSLNE.maksOdstepDni, WEKTORY.maximumInterval);
  });

  /* Every scenario is a test of its own rather than one loop over all of
     them: when it breaks we want the name to tell us WHICH path drifted. */
  for (const [nazwa, kroki] of Object.entries(WEKTORY.scenariusze)) {
    test(`scenario ${nazwa}`, () => {
      const F = silnik();
      let karta = null;
      /* The starting moment is arbitrary: the vectors carry intervals, not
         dates. What matters is that it is fixed - otherwise the test would be
         measuring the calendar. */
      let teraz = Date.UTC(2026, 0, 1, 12, 0, 0);

      kroki.forEach((oczekiwane, i) => {
        /* The moment of the review is carried by the vector itself: the card
           is graded exactly when it was graded in the generator. */
        teraz = teraz + oczekiwane.godzinOdPoprzedniej * 3600000;

        const przed = `${nazwa}#${i + 1} (${oczekiwane.ocena})`;
        assert.equal(karta ? karta.st : "learning", oczekiwane.przed.state, `${przed}: state before`);

        karta = F.powtorz(karta, OCENY[oczekiwane.ocena], teraz);

        assert.equal(karta.st, oczekiwane.po.state, `${przed}: state after`);
        assert.equal(karta.step, oczekiwane.po.step, `${przed}: step after`);
        assert.ok(
          Math.abs(karta.s - oczekiwane.po.stability) < TOL,
          `${przed}: stability ${karta.s} != ${oczekiwane.po.stability}`
        );
        assert.ok(
          Math.abs(karta.d - oczekiwane.po.difficulty) < TOL,
          `${przed}: difficulty ${karta.d} != ${oczekiwane.po.difficulty}`
        );
        assert.equal(
          Math.round((karta.due - teraz) / 1000),
          oczekiwane.odstepSekund,
          `${przed}: interval`
        );
      });
    });
  }
});

describe("fsrs: properties the vectors do not show directly", () => {
  test("the input card is not mutated", () => {
    const F = silnik();
    const karta = F.powtorz(null, F.DOBRZE, Date.UTC(2026, 0, 1));
    const kopia = JSON.parse(JSON.stringify(karta));
    F.powtorz(karta, F.ZNOWU, Date.UTC(2026, 0, 2));
    assert.deepEqual(JSON.parse(JSON.stringify(karta)), kopia, "the input is untouched");
  });

  test("a higher retention brings the due date closer", () => {
    const F = silnik();
    const luzny = F.silnik({ retencja: 0.8 });
    const ostry = F.silnik({ retencja: 0.95 });
    assert.ok(
      ostry.odstepDni(20) < luzny.odstepDni(20),
      "at 0.95 the same stability gives a shorter interval than at 0.8"
    );
  });

  test("a learning card moves into review after the last step instead of going round in circles", () => {
    /* The learning steps (1 min, 10 min) are a run-up, not a destination:
       after the last of them the card enters review with an interval computed
       from stability. Without that transition a new word would come back every
       ten minutes forever and the session would never end. */
    const F = silnik();
    const start = Date.UTC(2026, 0, 1);
    let karta = F.powtorz(null, F.DOBRZE, start);
    assert.equal(karta.st, "learning", "the first answer leaves the card in learning");
    assert.equal(karta.step, 1, "with the second step's interval, that is minutes");
    assert.ok(karta.due - start < 86400000, "still in the same session");

    karta = F.powtorz(karta, F.DOBRZE, start + 60000);
    assert.equal(karta.st, "review", "once the steps are done the card enters review");
    assert.equal(karta.step, null, "and stops having a step number");
    assert.ok(karta.due - (start + 60000) >= 86400000,
      "the interval comes from stability, not from the step list");
  });

  test("a card with a step outside the list does not stay in learning forever", () => {
    /* A profile saved with a longer step list comes back with a number that
       list no longer has. Without this branch such a card would have nowhere
       to go and would return in every session, looking like a word the student
       "cannot memorise". */
    const F = silnik();
    const teraz = Date.UTC(2026, 0, 5);
    const karta = F.powtorz(
      { st: "learning", step: 9, s: 3, d: 5, last: Date.UTC(2026, 0, 4) },
      F.DOBRZE, teraz
    );

    assert.equal(karta.st, "review");
    assert.equal(karta.step, null);
  });

  test("the interval never drops below a day nor exceeds the limit", () => {
    const F = silnik();
    const s = F.silnik(null);
    assert.equal(s.odstepDni(0.001), 1, "the minimum is one day");
    assert.equal(s.odstepDni(1e9), F.DOMYSLNE.maksOdstepDni, "clamped to the maximum");
  });

  test("retrievability decreases over time and starts at one", () => {
    const F = silnik();
    const s = F.silnik(null);
    assert.equal(s.odtwarzalnosc(10, 0), 1, "on the day of the review the chance is full");
    assert.ok(s.odtwarzalnosc(10, 10) < 1);
    assert.ok(s.odtwarzalnosc(10, 100) < s.odtwarzalnosc(10, 10));
  });

  test("after as many days as the interval, the chance settles on the requested retention", () => {
    const F = silnik();
    const s = F.silnik(null);
    const dni = s.odstepDni(30);
    assert.ok(
      Math.abs(s.odtwarzalnosc(30, dni) - 0.9) < 0.01,
      "this is the whole idea of FSRS: the interval sets a threshold, not a multiplier"
    );
  });
});
